package router

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

func InitRoutes(engine *gin.Engine) {
	// controller, err := controller.InitDocumentServiceController()
	// if err != nil {
	// 	common.WriteLog(1, err.Error())
	// 	panic(err)
	// }
	engine.GET("/", func(c *gin.Context) {

		var htmlBody = `<html>
		<head>
		<style>
		@media print
		{
		  table { page-break-after:auto }
		  tr    { page-break-inside:avoid; page-break-after:auto }
		  td    { page-break-inside:avoid; page-break-after:auto }
		  thead { display:table-header-group }
		  tfoot { display:table-footer-group }
		}
		</style>
		</head>
		
		<body>
		The Hindi Wikipedia (Hindi:   is the Hindi edition of Wikipedia. It was launched in July 2003. As of January 2022, it has 152,184 articles. In October 2021, there were 72 million page views.[1] On August 30, 2011, it became the first localized edition of Wikipedia in India to surpass 100,000 articles. Hindi, using the Devanagari script, requires complex transliteration aids to be typed on devices. Thus, a Phonetic Roman Alphabet converter is also available on the Hindi Wikipedia, so the Roman keyboard can be used to contribute in Hindi, without having to use any special Hindi-typing software.

Hindi Wikipedia is the second most popular Wikipedia in India after the English version. However, more than the 85% of Wikipedia pageviews by India still go to English, although between January 2016 and January 2021 the share of Hindi Wikipedia increased from 2% to 8%.[2] Most pageviews come from India. Hindi Wikipedia has more than 1,400 active users. In 2020 Hindi surpassed 2,000 active users for the first time, although in 2021 it has decreased due to COVID-19 pandemic. 
The Hindi Wikipedia (Hindi:   is the Hindi edition of Wikipedia. It was launched in July 2003. As of January 2022, it has 152,184 articles. In October 2021, there were 72 million page views.[1] On August 30, 2011, it became the first localized edition of Wikipedia in India to surpass 100,000 articles. Hindi, using the Devanagari script, requires complex transliteration aids to be typed on devices. Thus, a Phonetic Roman Alphabet converter is also available on the Hindi Wikipedia, so the Roman keyboard can be used to contribute in Hindi, without having to use any special Hindi-typing software.

Hindi Wikipedia is the second most popular Wikipedia in India after the English version. However, more than the 85% of Wikipedia pageviews by India still go to English, although between January 2016 and January 2021 the share of Hindi Wikipedia increased from 2% to 8%.[2] Most pageviews come from India. Hindi Wikipedia has more than 1,400 active users. In 2020 Hindi surpassed 2,000 active users for the first time, although in 2021 it has decreased due to COVID-19 pandemic. 
The Hindi Wikipedia (Hindi:   is the Hindi edition of Wikipedia. It was launched in July 2003. As of January 2022, it has 152,184 articles. In October 2021, there were 72 million page views.[1] On August 30, 2011, it became the first localized edition of Wikipedia in India to surpass 100,000 articles. Hindi, using the Devanagari script, requires complex transliteration aids to be typed on devices. Thus, a Phonetic Roman Alphabet converter is also available on the Hindi Wikipedia, so the Roman keyboard can be used to contribute in Hindi, without having to use any special Hindi-typing software.

Hindi Wikipedia is the second most popular Wikipedia in India after the English version. However, more than the 85% of Wikipedia pageviews by India still go to English, although between January 2016 and January 2021 the share of Hindi Wikipedia increased from 2% to 8%.[2] Most pageviews come from India. Hindi Wikipedia has more than 1,400 active users. In 2020 Hindi surpassed 2,000 active users for the first time, although in 2021 it has decreased due to COVID-19 pandemic. 
The Hindi Wikipedia (Hindi:   is the Hindi edition of Wikipedia. It was launched in July 2003. As of January 2022, it has 152,184 articles. In October 2021, there were 72 million page views.[1] On August 30, 2011, it became the first localized edition of Wikipedia in India to surpass 100,000 articles. Hindi, using the Devanagari script, requires complex transliteration aids to be typed on devices. Thus, a Phonetic Roman Alphabet converter is also available on the Hindi Wikipedia, so the Roman keyboard can be used to contribute in Hindi, without having to use any special Hindi-typing software.

Hindi Wikipedia is the second most popular Wikipedia in India after the English version. However, more than the 85% of Wikipedia pageviews by India still go to English, although between January 2016 and January 2021 the share of Hindi Wikipedia increased from 2% to 8%.[2] Most pageviews come from India. Hindi Wikipedia has more than 1,400 active users. In 2020 Hindi surpassed 2,000 active users for the first time, although in 2021 it has decreased due to COVID-19 pandemic. 
The Hindi Wikipedia (Hindi:   is the Hindi edition of Wikipedia. It was launched in July 2003. As of January 2022, it has 152,184 articles. In October 2021, there were 72 million page views.[1] On August 30, 2011, it became the first localized edition of Wikipedia in India to surpass 100,000 articles. Hindi, using the Devanagari script, requires complex transliteration aids to be typed on devices. Thus, a Phonetic Roman Alphabet converter is also available on the Hindi Wikipedia, so the Roman keyboard can be used to contribute in Hindi, without having to use any special Hindi-typing software.

Hindi Wikipedia is the second most popular Wikipedia in India after the English version. However, more than the 85% of Wikipedia pageviews by India still go to English, although between January 2016 and January 2021 the share of Hindi Wikipedia increased from 2% to 8%.[2] Most pageviews come from India. Hindi Wikipedia has more than 1,400 active users. In 2020 Hindi surpassed 2,000 active users for the first time, although in 2021 it has decreased due to COVID-19 pandemic. 
The Hindi Wikipedia (Hindi:   is the Hindi edition of Wikipedia. It was launched in July 2003. As of January 2022, it has 152,184 articles. In October 2021, there were 72 million page views.[1] On August 30, 2011, it became the first localized edition of Wikipedia in India to surpass 100,000 articles. Hindi, using the Devanagari script, requires complex transliteration aids to be typed on devices. Thus, a Phonetic Roman Alphabet converter is also available on the Hindi Wikipedia, so the Roman keyboard can be used to contribute in Hindi, without having to use any special Hindi-typing software.

Hindi Wikipedia is the second most popular Wikipedia in India after the English version. However, more than the 85% of Wikipedia pageviews by India still go to English, although between January 2016 and January 2021 the share of Hindi Wikipedia increased from 2% to 8%.[2] Most pageviews come from India. Hindi Wikipedia has more than 1,400 active users. In 2020 Hindi surpassed 2,000 active users for the first time, although in 2021 it has decreased due to COVID-19 pandemic. 
The Hindi Wikipedia (Hindi:   is the Hindi edition of Wikipedia. It was launched in July 2003. As of January 2022, it has 152,184 articles. In October 2021, there were 72 million page views.[1] On August 30, 2011, it became the first localized edition of Wikipedia in India to surpass 100,000 articles. Hindi, using the Devanagari script, requires complex transliteration aids to be typed on devices. Thus, a Phonetic Roman Alphabet converter is also available on the Hindi Wikipedia, so the Roman keyboard can be used to contribute in Hindi, without having to use any special Hindi-typing software.

Hindi Wikipedia is the second most popular Wikipedia in India after the English version. However, more than the 85% of Wikipedia pageviews by India still go to English, although between January 2016 and January 2021 the share of Hindi Wikipedia increased from 2% to 8%.[2] Most pageviews come from India. Hindi Wikipedia has more than 1,400 active users. In 2020 Hindi surpassed 2,000 active users for the first time, although in 2021 it has decreased due to COVID-19 pandemic. 
The Hindi Wikipedia (Hindi:   is the Hindi edition of Wikipedia. It was launched in July 2003. As of January 2022, it has 152,184 articles. In October 2021, there were 72 million page views.[1] On August 30, 2011, it became the first localized edition of Wikipedia in India to surpass 100,000 articles. Hindi, using the Devanagari script, requires complex transliteration aids to be typed on devices. Thus, a Phonetic Roman Alphabet converter is also available on the Hindi Wikipedia, so the Roman keyboard can be used to contribute in Hindi, without having to use any special Hindi-typing software.

Hindi Wikipedia is the second most popular Wikipedia in India after the English version. However, more than the 85% of Wikipedia pageviews by India still go to English, although between January 2016 and January 2021 the share of Hindi Wikipedia increased from 2% to 8%.[2] Most pageviews come from India. Hindi Wikipedia has more than 1,400 active users. In 2020 Hindi surpassed 2,000 active users for the first time, although in 2021 it has decreased due to COVID-19 pandemic. 
The Hindi Wikipedia (Hindi:   is the Hindi edition of Wikipedia. It was launched in July 2003. As of January 2022, it has 152,184 articles. In October 2021, there were 72 million page views.[1] On August 30, 2011, it became the first localized edition of Wikipedia in India to surpass 100,000 articles. Hindi, using the Devanagari script, requires complex transliteration aids to be typed on devices. Thus, a Phonetic Roman Alphabet converter is also available on the Hindi Wikipedia, so the Roman keyboard can be used to contribute in Hindi, without having to use any special Hindi-typing software.

Hindi Wikipedia is the second most popular Wikipedia in India after the English version. However, more than the 85% of Wikipedia pageviews by India still go to English, although between January 2016 and January 2021 the share of Hindi Wikipedia increased from 2% to 8%.[2] Most pageviews come from India. Hindi Wikipedia has more than 1,400 active users. In 2020 Hindi surpassed 2,000 active users for the first time, although in 2021 it has decreased due to COVID-19 pandemic. 
The Hindi Wikipedia (Hindi:   is the Hindi edition of Wikipedia. It was launched in July 2003. As of January 2022, it has 152,184 articles. In October 2021, there were 72 million page views.[1] On August 30, 2011, it became the first localized edition of Wikipedia in India to surpass 100,000 articles. Hindi, using the Devanagari script, requires complex transliteration aids to be typed on devices. Thus, a Phonetic Roman Alphabet converter is also available on the Hindi Wikipedia, so the Roman keyboard can be used to contribute in Hindi, without having to use any special Hindi-typing software.

Hindi Wikipedia is the second most popular Wikipedia in India after the English version. However, more than the 85% of Wikipedia pageviews by India still go to English, although between January 2016 and January 2021 the share of Hindi Wikipedia increased from 2% to 8%.[2] Most pageviews come from India. Hindi Wikipedia has more than 1,400 active users. In 2020 Hindi surpassed 2,000 active users for the first time, although in 2021 it has decreased due to COVID-19 pandemic. 
The Hindi Wikipedia (Hindi:   is the Hindi edition of Wikipedia. It was launched in July 2003. As of January 2022, it has 152,184 articles. In October 2021, there were 72 million page views.[1] On August 30, 2011, it became the first localized edition of Wikipedia in India to surpass 100,000 articles. Hindi, using the Devanagari script, requires complex transliteration aids to be typed on devices. Thus, a Phonetic Roman Alphabet converter is also available on the Hindi Wikipedia, so the Roman keyboard can be used to contribute in Hindi, without having to use any special Hindi-typing software.

Hindi Wikipedia is the second most popular Wikipedia in India after the English version. However, more than the 85% of Wikipedia pageviews by India still go to English, although between January 2016 and January 2021 the share of Hindi Wikipedia increased from 2% to 8%.[2] Most pageviews come from India. Hindi Wikipedia has more than 1,400 active users. In 2020 Hindi surpassed 2,000 active users for the first time, although in 2021 it has decreased due to COVID-19 pandemic. 
The Hindi Wikipedia (Hindi:   is the Hindi edition of Wikipedia. It was launched in July 2003. As of January 2022, it has 152,184 articles. In October 2021, there were 72 million page views.[1] On August 30, 2011, it became the first localized edition of Wikipedia in India to surpass 100,000 articles. Hindi, using the Devanagari script, requires complex transliteration aids to be typed on devices. Thus, a Phonetic Roman Alphabet converter is also available on the Hindi Wikipedia, so the Roman keyboard can be used to contribute in Hindi, without having to use any special Hindi-typing software.

Hindi Wikipedia is the second most popular Wikipedia in India after the English version. However, more than the 85% of Wikipedia pageviews by India still go to English, although between January 2016 and January 2021 the share of Hindi Wikipedia increased from 2% to 8%.[2] Most pageviews come from India. Hindi Wikipedia has more than 1,400 active users. In 2020 Hindi surpassed 2,000 active users for the first time, although in 2021 it has decreased due to COVID-19 pandemic. 
The Hindi Wikipedia (Hindi:   is the Hindi edition of Wikipedia. It was launched in July 2003. As of January 2022, it has 152,184 articles. In October 2021, there were 72 million page views.[1] On August 30, 2011, it became the first localized edition of Wikipedia in India to surpass 100,000 articles. Hindi, using the Devanagari script, requires complex transliteration aids to be typed on devices. Thus, a Phonetic Roman Alphabet converter is also available on the Hindi Wikipedia, so the Roman keyboard can be used to contribute in Hindi, without having to use any special Hindi-typing software.

Hindi Wikipedia is the second most popular Wikipedia in India after the English version. However, more than the 85% of Wikipedia pageviews by India still go to English, although between January 2016 and January 2021 the share of Hindi Wikipedia increased from 2% to 8%.[2] Most pageviews come from India. Hindi Wikipedia has more than 1,400 active users. In 2020 Hindi surpassed 2,000 active users for the first time, although in 2021 it has decreased due to COVID-19 pandemic. 
The Hindi Wikipedia (Hindi:   is the Hindi edition of Wikipedia. It was launched in July 2003. As of January 2022, it has 152,184 articles. In October 2021, there were 72 million page views.[1] On August 30, 2011, it became the first localized edition of Wikipedia in India to surpass 100,000 articles. Hindi, using the Devanagari script, requires complex transliteration aids to be typed on devices. Thus, a Phonetic Roman Alphabet converter is also available on the Hindi Wikipedia, so the Roman keyboard can be used to contribute in Hindi, without having to use any special Hindi-typing software.

Hindi Wikipedia is the second most popular Wikipedia in India after the English version. However, more than the 85% of Wikipedia pageviews by India still go to English, although between January 2016 and January 2021 the share of Hindi Wikipedia increased from 2% to 8%.[2] Most pageviews come from India. Hindi Wikipedia has more than 1,400 active users. In 2020 Hindi surpassed 2,000 active users for the first time, although in 2021 it has decreased due to COVID-19 pandemic. 
The Hindi Wikipedia (Hindi:   is the Hindi edition of Wikipedia. It was launched in July 2003. As of January 2022, it has 152,184 articles. In October 2021, there were 72 million page views.[1] On August 30, 2011, it became the first localized edition of Wikipedia in India to surpass 100,000 articles. Hindi, using the Devanagari script, requires complex transliteration aids to be typed on devices. Thus, a Phonetic Roman Alphabet converter is also available on the Hindi Wikipedia, so the Roman keyboard can be used to contribute in Hindi, without having to use any special Hindi-typing software.

Hindi Wikipedia is the second most popular Wikipedia in India after the English version. However, more than the 85% of Wikipedia pageviews by India still go to English, although between January 2016 and January 2021 the share of Hindi Wikipedia increased from 2% to 8%.[2] Most pageviews come from India. Hindi Wikipedia has more than 1,400 active users. In 2020 Hindi surpassed 2,000 active users for the first time, although in 2021 it has decreased due to COVID-19 pandemic. 
The Hindi Wikipedia (Hindi:   is the Hindi edition of Wikipedia. It was launched in July 2003. As of January 2022, it has 152,184 articles. In October 2021, there were 72 million page views.[1] On August 30, 2011, it became the first localized edition of Wikipedia in India to surpass 100,000 articles. Hindi, using the Devanagari script, requires complex transliteration aids to be typed on devices. Thus, a Phonetic Roman Alphabet converter is also available on the Hindi Wikipedia, so the Roman keyboard can be used to contribute in Hindi, without having to use any special Hindi-typing software.

Hindi Wikipedia is the second most popular Wikipedia in India after the English version. However, more than the 85% of Wikipedia pageviews by India still go to English, although between January 2016 and January 2021 the share of Hindi Wikipedia increased from 2% to 8%.[2] Most pageviews come from India. Hindi Wikipedia has more than 1,400 active users. In 2020 Hindi surpassed 2,000 active users for the first time, although in 2021 it has decreased due to COVID-19 pandemic. The Hindi Wikipedia (Hindi:   is the Hindi edition of Wikipedia. It was launched in July 2003. As of January 2022, it has 152,184 articles. In October 2021, there were 72 million page views.[1] On August 30, 2011, it became the first localized edition of Wikipedia in India to surpass 100,000 articles. Hindi, using the Devanagari script, requires complex transliteration aids to be typed on devices. Thus, a Phonetic Roman Alphabet converter is also available on the Hindi Wikipedia, so the Roman keyboard can be used to contribute in Hindi, without having to use any special Hindi-typing software.

Hindi Wikipedia is the second most popular Wikipedia in India after the English version. However, more than the 85% of Wikipedia pageviews by India still go to English, although between January 2016 and January 2021 the share of Hindi Wikipedia increased from 2% to 8%.[2] Most pageviews come from India. Hindi Wikipedia has more than 1,400 active users. In 2020 Hindi surpassed 2,000 active users for the first time, although in 2021 it has decreased due to COVID-19 pandemic. 
The Hindi Wikipedia (Hindi:   is the Hindi edition of Wikipedia. It was launched in July 2003. As of January 2022, it has 152,184 articles. In October 2021, there were 72 million page views.[1] On August 30, 2011, it became the first localized edition of Wikipedia in India to surpass 100,000 articles. Hindi, using the Devanagari script, requires complex transliteration aids to be typed on devices. Thus, a Phonetic Roman Alphabet converter is also available on the Hindi Wikipedia, so the Roman keyboard can be used to contribute in Hindi, without having to use any special Hindi-typing software.

Hindi Wikipedia is the second most popular Wikipedia in India after the English version. However, more than the 85% of Wikipedia pageviews by India still go to English, although between January 2016 and January 2021 the share of Hindi Wikipedia increased from 2% to 8%.[2] Most pageviews come from India. Hindi Wikipedia has more than 1,400 active users. In 2020 Hindi surpassed 2,000 active users for the first time, although in 2021 it has decreased due to COVID-19 pandemic. 
The Hindi Wikipedia (Hindi:   is the Hindi edition of Wikipedia. It was launched in July 2003. As of January 2022, it has 152,184 articles. In October 2021, there were 72 million page views.[1] On August 30, 2011, it became the first localized edition of Wikipedia in India to surpass 100,000 articles. Hindi, using the Devanagari script, requires complex transliteration aids to be typed on devices. Thus, a Phonetic Roman Alphabet converter is also available on the Hindi Wikipedia, so the Roman keyboard can be used to contribute in Hindi, without having to use any special Hindi-typing software.

Hindi Wikipedia is the second most popular Wikipedia in India after the English version. However, more than the 85% of Wikipedia pageviews by India still go to English, although between January 2016 and January 2021 the share of Hindi Wikipedia increased from 2% to 8%.[2] Most pageviews come from India. Hindi Wikipedia has more than 1,400 active users. In 2020 Hindi surpassed 2,000 active users for the first time, although in 2021 it has decreased due to COVID-19 pandemic. 
The Hindi Wikipedia (Hindi:   is the Hindi edition of Wikipedia. It was launched in July 2003. As of January 2022, it has 152,184 articles. In October 2021, there were 72 million page views.[1] On August 30, 2011, it became the first localized edition of Wikipedia in India to surpass 100,000 articles. Hindi, using the Devanagari script, requires complex transliteration aids to be typed on devices. Thus, a Phonetic Roman Alphabet converter is also available on the Hindi Wikipedia, so the Roman keyboard can be used to contribute in Hindi, without having to use any special Hindi-typing software.

Hindi Wikipedia is the second most popular Wikipedia in India after the English version. However, more than the 85% of Wikipedia pageviews by India still go to English, although between January 2016 and January 2021 the share of Hindi Wikipedia increased from 2% to 8%.[2] Most pageviews come from India. Hindi Wikipedia has more than 1,400 active users. In 2020 Hindi surpassed 2,000 active users for the first time, although in 2021 it has decreased due to COVID-19 pandemic. 
The Hindi Wikipedia (Hindi:   is the Hindi edition of Wikipedia. It was launched in July 2003. As of January 2022, it has 152,184 articles. In October 2021, there were 72 million page views.[1] On August 30, 2011, it became the first localized edition of Wikipedia in India to surpass 100,000 articles. Hindi, using the Devanagari script, requires complex transliteration aids to be typed on devices. Thus, a Phonetic Roman Alphabet converter is also available on the Hindi Wikipedia, so the Roman keyboard can be used to contribute in Hindi, without having to use any special Hindi-typing software.

Hindi Wikipedia is the second most popular Wikipedia in India after the English version. However, more than the 85% of Wikipedia pageviews by India still go to English, although between January 2016 and January 2021 the share of Hindi Wikipedia increased from 2% to 8%.[2] Most pageviews come from India. Hindi Wikipedia has more than 1,400 active users. In 2020 Hindi surpassed 2,000 active users for the first time, although in 2021 it has decreased due to COVID-19 pandemic. 
The Hindi Wikipedia (Hindi:   is the Hindi edition of Wikipedia. It was launched in July 2003. As of January 2022, it has 152,184 articles. In October 2021, there were 72 million page views.[1] On August 30, 2011, it became the first localized edition of Wikipedia in India to surpass 100,000 articles. Hindi, using the Devanagari script, requires complex transliteration aids to be typed on devices. Thus, a Phonetic Roman Alphabet converter is also available on the Hindi Wikipedia, so the Roman keyboard can be used to contribute in Hindi, without having to use any special Hindi-typing software.

Hindi Wikipedia is the second most popular Wikipedia in India after the English version. However, more than the 85% of Wikipedia pageviews by India still go to English, although between January 2016 and January 2021 the share of Hindi Wikipedia increased from 2% to 8%.[2] Most pageviews come from India. Hindi Wikipedia has more than 1,400 active users. In 2020 Hindi surpassed 2,000 active users for the first time, although in 2021 it has decreased due to COVID-19 pandemic. 
The Hindi Wikipedia (Hindi:   is the Hindi edition of Wikipedia. It was launched in July 2003. As of January 2022, it has 152,184 articles. In October 2021, there were 72 million page views.[1] On August 30, 2011, it became the first localized edition of Wikipedia in India to surpass 100,000 articles. Hindi, using the Devanagari script, requires complex transliteration aids to be typed on devices. Thus, a Phonetic Roman Alphabet converter is also available on the Hindi Wikipedia, so the Roman keyboard can be used to contribute in Hindi, without having to use any special Hindi-typing software.

Hindi Wikipedia is the second most popular Wikipedia in India after the English version. However, more than the 85% of Wikipedia pageviews by India still go to English, although between January 2016 and January 2021 the share of Hindi Wikipedia increased from 2% to 8%.[2] Most pageviews come from India. Hindi Wikipedia has more than 1,400 active users. In 2020 Hindi surpassed 2,000 active users for the first time, although in 2021 it has decreased due to COVID-19 pandemic. 
The Hindi Wikipedia (Hindi:   is the Hindi edition of Wikipedia. It was launched in July 2003. As of January 2022, it has 152,184 articles. In October 2021, there were 72 million page views.[1] On August 30, 2011, it became the first localized edition of Wikipedia in India to surpass 100,000 articles. Hindi, using the Devanagari script, requires complex transliteration aids to be typed on devices. Thus, a Phonetic Roman Alphabet converter is also available on the Hindi Wikipedia, so the Roman keyboard can be used to contribute in Hindi, without having to use any special Hindi-typing software.

Hindi Wikipedia is the second most popular Wikipedia in India after the English version. However, more than the 85% of Wikipedia pageviews by India still go to English, although between January 2016 and January 2021 the share of Hindi Wikipedia increased from 2% to 8%.[2] Most pageviews come from India. Hindi Wikipedia has more than 1,400 active users. In 2020 Hindi surpassed 2,000 active users for the first time, although in 2021 it has decreased due to COVID-19 pandemic. 
The Hindi Wikipedia (Hindi:   is the Hindi edition of Wikipedia. It was launched in July 2003. As of January 2022, it has 152,184 articles. In October 2021, there were 72 million page views.[1] On August 30, 2011, it became the first localized edition of Wikipedia in India to surpass 100,000 articles. Hindi, using the Devanagari script, requires complex transliteration aids to be typed on devices. Thus, a Phonetic Roman Alphabet converter is also available on the Hindi Wikipedia, so the Roman keyboard can be used to contribute in Hindi, without having to use any special Hindi-typing software.

Hindi Wikipedia is the second most popular Wikipedia in India after the English version. However, more than the 85% of Wikipedia pageviews by India still go to English, although between January 2016 and January 2021 the share of Hindi Wikipedia increased from 2% to 8%.[2] Most pageviews come from India. Hindi Wikipedia has more than 1,400 active users. In 2020 Hindi surpassed 2,000 active users for the first time, although in 2021 it has decreased due to COVID-19 pandemic. 
The Hindi Wikipedia (Hindi:   is the Hindi edition of Wikipedia. It was launched in July 2003. As of January 2022, it has 152,184 articles. In October 2021, there were 72 million page views.[1] On August 30, 2011, it became the first localized edition of Wikipedia in India to surpass 100,000 articles. Hindi, using the Devanagari script, requires complex transliteration aids to be typed on devices. Thus, a Phonetic Roman Alphabet converter is also available on the Hindi Wikipedia, so the Roman keyboard can be used to contribute in Hindi, without having to use any special Hindi-typing software.

Hindi Wikipedia is the second most popular Wikipedia in India after the English version. However, more than the 85% of Wikipedia pageviews by India still go to English, although between January 2016 and January 2021 the share of Hindi Wikipedia increased from 2% to 8%.[2] Most pageviews come from India. Hindi Wikipedia has more than 1,400 active users. In 2020 Hindi surpassed 2,000 active users for the first time, although in 2021 it has decreased due to COVID-19 pandemic. The Hindi Wikipedia (Hindi:   is the Hindi edition of Wikipedia. It was launched in July 2003. As of January 2022, it has 152,184 articles. In October 2021, there were 72 million page views.[1] On August 30, 2011, it became the first localized edition of Wikipedia in India to surpass 100,000 articles. Hindi, using the Devanagari script, requires complex transliteration aids to be typed on devices. Thus, a Phonetic Roman Alphabet converter is also available on the Hindi Wikipedia, so the Roman keyboard can be used to contribute in Hindi, without having to use any special Hindi-typing software.

Hindi Wikipedia is the second most popular Wikipedia in India after the English version. However, more than the 85% of Wikipedia pageviews by India still go to English, although between January 2016 and January 2021 the share of Hindi Wikipedia increased from 2% to 8%.[2] Most pageviews come from India. Hindi Wikipedia has more than 1,400 active users. In 2020 Hindi surpassed 2,000 active users for the first time, although in 2021 it has decreased due to COVID-19 pandemic. The Hindi Wikipedia (Hindi:   is the Hindi edition of Wikipedia. It was launched in July 2003. As of January 2022, it has 152,184 articles. In October 2021, there were 72 million page views.[1] On August 30, 2011, it became the first localized edition of Wikipedia in India to surpass 100,000 articles. Hindi, using the Devanagari script, requires complex transliteration aids to be typed on devices. Thus, a Phonetic Roman Alphabet converter is also available on the Hindi Wikipedia, so the Roman keyboard can be used to contribute in Hindi, without having to use any special Hindi-typing software.

Hindi Wikipedia is the second most popular Wikipedia in India after the English version. However, more than the 85% of Wikipedia pageviews by India still go to English, although between January 2016 and January 2021 the share of Hindi Wikipedia increased from 2% to 8%.[2] Most pageviews come from India. Hindi Wikipedia has more than 1,400 active users. In 2020 Hindi surpassed 2,000 active users for the first time, although in 2021 it has decreased due to COVID-19 pandemic. 
The Hindi Wikipedia (Hindi:   is the Hindi edition of Wikipedia. It was launched in July 2003. As of January 2022, it has 152,184 articles. In October 2021, there were 72 million page views.[1] On August 30, 2011, it became the first localized edition of Wikipedia in India to surpass 100,000 articles. Hindi, using the Devanagari script, requires complex transliteration aids to be typed on devices. Thus, a Phonetic Roman Alphabet converter is also available on the Hindi Wikipedia, so the Roman keyboard can be used to contribute in Hindi, without having to use any special Hindi-typing software.

Hindi Wikipedia is the second most popular Wikipedia in India after the English version. However, more than the 85% of Wikipedia pageviews by India still go to English, although between January 2016 and January 2021 the share of Hindi Wikipedia increased from 2% to 8%.[2] Most pageviews come from India. Hindi Wikipedia has more than 1,400 active users. In 2020 Hindi surpassed 2,000 active users for the first time, although in 2021 it has decreased due to COVID-19 pandemic. 
The Hindi Wikipedia (Hindi:   is the Hindi edition of Wikipedia. It was launched in July 2003. As of January 2022, it has 152,184 articles. In October 2021, there were 72 million page views.[1] On August 30, 2011, it became the first localized edition of Wikipedia in India to surpass 100,000 articles. Hindi, using the Devanagari script, requires complex transliteration aids to be typed on devices. Thus, a Phonetic Roman Alphabet converter is also available on the Hindi Wikipedia, so the Roman keyboard can be used to contribute in Hindi, without having to use any special Hindi-typing software.

Hindi Wikipedia is the second most popular Wikipedia in India after the English version. However, more than the 85% of Wikipedia pageviews by India still go to English, although between January 2016 and January 2021 the share of Hindi Wikipedia increased from 2% to 8%.[2] Most pageviews come from India. Hindi Wikipedia has more than 1,400 active users. In 2020 Hindi surpassed 2,000 active users for the first time, although in 2021 it has decreased due to COVID-19 pandemic. 
The Hindi Wikipedia (Hindi:   is the Hindi edition of Wikipedia. It was launched in July 2003. As of January 2022, it has 152,184 articles. In October 2021, there were 72 million page views.[1] On August 30, 2011, it became the first localized edition of Wikipedia in India to surpass 100,000 articles. Hindi, using the Devanagari script, requires complex transliteration aids to be typed on devices. Thus, a Phonetic Roman Alphabet converter is also available on the Hindi Wikipedia, so the Roman keyboard can be used to contribute in Hindi, without having to use any special Hindi-typing software.

Hindi Wikipedia is the second most popular Wikipedia in India after the English version. However, more than the 85% of Wikipedia pageviews by India still go to English, although between January 2016 and January 2021 the share of Hindi Wikipedia increased from 2% to 8%.[2] Most pageviews come from India. Hindi Wikipedia has more than 1,400 active users. In 2020 Hindi surpassed 2,000 active users for the first time, although in 2021 it has decreased due to COVID-19 pandemic. 
The Hindi Wikipedia (Hindi:   is the Hindi edition of Wikipedia. It was launched in July 2003. As of January 2022, it has 152,184 articles. In October 2021, there were 72 million page views.[1] On August 30, 2011, it became the first localized edition of Wikipedia in India to surpass 100,000 articles. Hindi, using the Devanagari script, requires complex transliteration aids to be typed on devices. Thus, a Phonetic Roman Alphabet converter is also available on the Hindi Wikipedia, so the Roman keyboard can be used to contribute in Hindi, without having to use any special Hindi-typing software.

Hindi Wikipedia is the second most popular Wikipedia in India after the English version. However, more than the 85% of Wikipedia pageviews by India still go to English, although between January 2016 and January 2021 the share of Hindi Wikipedia increased from 2% to 8%.[2] Most pageviews come from India. Hindi Wikipedia has more than 1,400 active users. In 2020 Hindi surpassed 2,000 active users for the first time, although in 2021 it has decreased due to COVID-19 pandemic. 
The Hindi Wikipedia (Hindi:   is the Hindi edition of Wikipedia. It was launched in July 2003. As of January 2022, it has 152,184 articles. In October 2021, there were 72 million page views.[1] On August 30, 2011, it became the first localized edition of Wikipedia in India to surpass 100,000 articles. Hindi, using the Devanagari script, requires complex transliteration aids to be typed on devices. Thus, a Phonetic Roman Alphabet converter is also available on the Hindi Wikipedia, so the Roman keyboard can be used to contribute in Hindi, without having to use any special Hindi-typing software.

Hindi Wikipedia is the second most popular Wikipedia in India after the English version. However, more than the 85% of Wikipedia pageviews by India still go to English, although between January 2016 and January 2021 the share of Hindi Wikipedia increased from 2% to 8%.[2] Most pageviews come from India. Hindi Wikipedia has more than 1,400 active users. In 2020 Hindi surpassed 2,000 active users for the first time, although in 2021 it has decreased due to COVID-19 pandemic. 
The Hindi Wikipedia (Hindi:   is the Hindi edition of Wikipedia. It was launched in July 2003. As of January 2022, it has 152,184 articles. In October 2021, there were 72 million page views.[1] On August 30, 2011, it became the first localized edition of Wikipedia in India to surpass 100,000 articles. Hindi, using the Devanagari script, requires complex transliteration aids to be typed on devices. Thus, a Phonetic Roman Alphabet converter is also available on the Hindi Wikipedia, so the Roman keyboard can be used to contribute in Hindi, without having to use any special Hindi-typing software.

Hindi Wikipedia is the second most popular Wikipedia in India after the English version. However, more than the 85% of Wikipedia pageviews by India still go to English, although between January 2016 and January 2021 the share of Hindi Wikipedia increased from 2% to 8%.[2] Most pageviews come from India. Hindi Wikipedia has more than 1,400 active users. In 2020 Hindi surpassed 2,000 active users for the first time, although in 2021 it has decreased due to COVID-19 pandemic. The Hindi Wikipedia (Hindi:   is the Hindi edition of Wikipedia. It was launched in July 2003. As of January 2022, it has 152,184 articles. In October 2021, there were 72 million page views.[1] On August 30, 2011, it became the first localized edition of Wikipedia in India to surpass 100,000 articles. Hindi, using the Devanagari script, requires complex transliteration aids to be typed on devices. Thus, a Phonetic Roman Alphabet converter is also available on the Hindi Wikipedia, so the Roman keyboard can be used to contribute in Hindi, without having to use any special Hindi-typing software.

Hindi Wikipedia is the second most popular Wikipedia in India after the English version. However, more than the 85% of Wikipedia pageviews by India still go to English, although between January 2016 and January 2021 the share of Hindi Wikipedia increased from 2% to 8%.[2] Most pageviews come from India. Hindi Wikipedia has more than 1,400 active users. In 2020 Hindi surpassed 2,000 active users for the first time, although in 2021 it has decreased due to COVID-19 pandemic. The Hindi Wikipedia (Hindi:   is the Hindi edition of Wikipedia. It was launched in July 2003. As of January 2022, it has 152,184 articles. In October 2021, there were 72 million page views.[1] On August 30, 2011, it became the first localized edition of Wikipedia in India to surpass 100,000 articles. Hindi, using the Devanagari script, requires complex transliteration aids to be typed on devices. Thus, a Phonetic Roman Alphabet converter is also available on the Hindi Wikipedia, so the Roman keyboard can be used to contribute in Hindi, without having to use any special Hindi-typing software.

Hindi Wikipedia is the second most popular Wikipedia in India after the English version. However, more than the 85% of Wikipedia pageviews by India still go to English, although between January 2016 and January 2021 the share of Hindi Wikipedia increased from 2% to 8%.[2] Most pageviews come from India. Hindi Wikipedia has more than 1,400 active users. In 2020 Hindi surpassed 2,000 active users for the first time, although in 2021 it has decreased due to COVID-19 pandemic. 
The Hindi Wikipedia (Hindi:   is the Hindi edition of Wikipedia. It was launched in July 2003. As of January 2022, it has 152,184 articles. In October 2021, there were 72 million page views.[1] On August 30, 2011, it became the first localized edition of Wikipedia in India to surpass 100,000 articles. Hindi, using the Devanagari script, requires complex transliteration aids to be typed on devices. Thus, a Phonetic Roman Alphabet converter is also available on the Hindi Wikipedia, so the Roman keyboard can be used to contribute in Hindi, without having to use any special Hindi-typing software.

Hindi Wikipedia is the second most popular Wikipedia in India after the English version. However, more than the 85% of Wikipedia pageviews by India still go to English, although between January 2016 and January 2021 the share of Hindi Wikipedia increased from 2% to 8%.[2] Most pageviews come from India. Hindi Wikipedia has more than 1,400 active users. In 2020 Hindi surpassed 2,000 active users for the first time, although in 2021 it has decreased due to COVID-19 pandemic. 
The Hindi Wikipedia (Hindi:   is the Hindi edition of Wikipedia. It was launched in July 2003. As of January 2022, it has 152,184 articles. In October 2021, there were 72 million page views.[1] On August 30, 2011, it became the first localized edition of Wikipedia in India to surpass 100,000 articles. Hindi, using the Devanagari script, requires complex transliteration aids to be typed on devices. Thus, a Phonetic Roman Alphabet converter is also available on the Hindi Wikipedia, so the Roman keyboard can be used to contribute in Hindi, without having to use any special Hindi-typing software.

Hindi Wikipedia is the second most popular Wikipedia in India after the English version. However, more than the 85% of Wikipedia pageviews by India still go to English, although between January 2016 and January 2021 the share of Hindi Wikipedia increased from 2% to 8%.[2] Most pageviews come from India. Hindi Wikipedia has more than 1,400 active users. In 2020 Hindi surpassed 2,000 active users for the first time, although in 2021 it has decreased due to COVID-19 pandemic. 
The Hindi Wikipedia (Hindi:   is the Hindi edition of Wikipedia. It was launched in July 2003. As of January 2022, it has 152,184 articles. In October 2021, there were 72 million page views.[1] On August 30, 2011, it became the first localized edition of Wikipedia in India to surpass 100,000 articles. Hindi, using the Devanagari script, requires complex transliteration aids to be typed on devices. Thus, a Phonetic Roman Alphabet converter is also available on the Hindi Wikipedia, so the Roman keyboard can be used to contribute in Hindi, without having to use any special Hindi-typing software.

Hindi Wikipedia is the second most popular Wikipedia in India after the English version. However, more than the 85% of Wikipedia pageviews by India still go to English, although between January 2016 and January 2021 the share of Hindi Wikipedia increased from 2% to 8%.[2] Most pageviews come from India. Hindi Wikipedia has more than 1,400 active users. In 2020 Hindi surpassed 2,000 active users for the first time, although in 2021 it has decreased due to COVID-19 pandemic. 
The Hindi Wikipedia (Hindi:   is the Hindi edition of Wikipedia. It was launched in July 2003. As of January 2022, it has 152,184 articles. In October 2021, there were 72 million page views.[1] On August 30, 2011, it became the first localized edition of Wikipedia in India to surpass 100,000 articles. Hindi, using the Devanagari script, requires complex transliteration aids to be typed on devices. Thus, a Phonetic Roman Alphabet converter is also available on the Hindi Wikipedia, so the Roman keyboard can be used to contribute in Hindi, without having to use any special Hindi-typing software.

Hindi Wikipedia is the second most popular Wikipedia in India after the English version. However, more than the 85% of Wikipedia pageviews by India still go to English, although between January 2016 and January 2021 the share of Hindi Wikipedia increased from 2% to 8%.[2] Most pageviews come from India. Hindi Wikipedia has more than 1,400 active users. In 2020 Hindi surpassed 2,000 active users for the first time, although in 2021 it has decreased due to COVID-19 pandemic. 
The Hindi Wikipedia (Hindi:   is the Hindi edition of Wikipedia. It was launched in July 2003. As of January 2022, it has 152,184 articles. In October 2021, there were 72 million page views.[1] On August 30, 2011, it became the first localized edition of Wikipedia in India to surpass 100,000 articles. Hindi, using the Devanagari script, requires complex transliteration aids to be typed on devices. Thus, a Phonetic Roman Alphabet converter is also available on the Hindi Wikipedia, so the Roman keyboard can be used to contribute in Hindi, without having to use any special Hindi-typing software.

Hindi Wikipedia is the second most popular Wikipedia in India after the English version. However, more than the 85% of Wikipedia pageviews by India still go to English, although between January 2016 and January 2021 the share of Hindi Wikipedia increased from 2% to 8%.[2] Most pageviews come from India. Hindi Wikipedia has more than 1,400 active users. In 2020 Hindi surpassed 2,000 active users for the first time, although in 2021 it has decreased due to COVID-19 pandemic. 
The Hindi Wikipedia (Hindi:   is the Hindi edition of Wikipedia. It was launched in July 2003. As of January 2022, it has 152,184 articles. In October 2021, there were 72 million page views.[1] On August 30, 2011, it became the first localized edition of Wikipedia in India to surpass 100,000 articles. Hindi, using the Devanagari script, requires complex transliteration aids to be typed on devices. Thus, a Phonetic Roman Alphabet converter is also available on the Hindi Wikipedia, so the Roman keyboard can be used to contribute in Hindi, without having to use any special Hindi-typing software.

Hindi Wikipedia is the second most popular Wikipedia in India after the English version. However, more than the 85% of Wikipedia pageviews by India still go to English, although between January 2016 and January 2021 the share of Hindi Wikipedia increased from 2% to 8%.[2] Most pageviews come from India. Hindi Wikipedia has more than 1,400 active users. In 2020 Hindi surpassed 2,000 active users for the first time, although in 2021 it has decreased due to COVID-19 pandemic. 
The Hindi Wikipedia (Hindi:   is the Hindi edition of Wikipedia. It was launched in July 2003. As of January 2022, it has 152,184 articles. In October 2021, there were 72 million page views.[1] On August 30, 2011, it became the first localized edition of Wikipedia in India to surpass 100,000 articles. Hindi, using the Devanagari script, requires complex transliteration aids to be typed on devices. Thus, a Phonetic Roman Alphabet converter is also available on the Hindi Wikipedia, so the Roman keyboard can be used to contribute in Hindi, without having to use any special Hindi-typing software.

Hindi Wikipedia is the second most popular Wikipedia in India after the English version. However, more than the 85% of Wikipedia pageviews by India still go to English, although between January 2016 and January 2021 the share of Hindi Wikipedia increased from 2% to 8%.[2] Most pageviews come from India. Hindi Wikipedia has more than 1,400 active users. In 2020 Hindi surpassed 2,000 active users for the first time, although in 2021 it has decreased due to COVID-19 pandemic. 
The Hindi Wikipedia (Hindi:   is the Hindi edition of Wikipedia. It was launched in July 2003. As of January 2022, it has 152,184 articles. In October 2021, there were 72 million page views.[1] On August 30, 2011, it became the first localized edition of Wikipedia in India to surpass 100,000 articles. Hindi, using the Devanagari script, requires complex transliteration aids to be typed on devices. Thus, a Phonetic Roman Alphabet converter is also available on the Hindi Wikipedia, so the Roman keyboard can be used to contribute in Hindi, without having to use any special Hindi-typing software.

Hindi Wikipedia is the second most popular Wikipedia in India after the English version. However, more than the 85% of Wikipedia pageviews by India still go to English, although between January 2016 and January 2021 the share of Hindi Wikipedia increased from 2% to 8%.[2] Most pageviews come from India. Hindi Wikipedia has more than 1,400 active users. In 2020 Hindi surpassed 2,000 active users for the first time, although in 2021 it has decreased due to COVID-19 pandemic. 
The Hindi Wikipedia (Hindi:   is the Hindi edition of Wikipedia. It was launched in July 2003. As of January 2022, it has 152,184 articles. In October 2021, there were 72 million page views.[1] On August 30, 2011, it became the first localized edition of Wikipedia in India to surpass 100,000 articles. Hindi, using the Devanagari script, requires complex transliteration aids to be typed on devices. Thus, a Phonetic Roman Alphabet converter is also available on the Hindi Wikipedia, so the Roman keyboard can be used to contribute in Hindi, without having to use any special Hindi-typing software.

Hindi Wikipedia is the second most popular Wikipedia in India after the English version. However, more than the 85% of Wikipedia pageviews by India still go to English, although between January 2016 and January 2021 the share of Hindi Wikipedia increased from 2% to 8%.[2] Most pageviews come from India. Hindi Wikipedia has more than 1,400 active users. In 2020 Hindi surpassed 2,000 active users for the first time, although in 2021 it has decreased due to COVID-19 pandemic. 
The Hindi Wikipedia (Hindi:   is the Hindi edition of Wikipedia. It was launched in July 2003. As of January 2022, it has 152,184 articles. In October 2021, there were 72 million page views.[1] On August 30, 2011, it became the first localized edition of Wikipedia in India to surpass 100,000 articles. Hindi, using the Devanagari script, requires complex transliteration aids to be typed on devices. Thus, a Phonetic Roman Alphabet converter is also available on the Hindi Wikipedia, so the Roman keyboard can be used to contribute in Hindi, without having to use any special Hindi-typing software.

Hindi Wikipedia is the second most popular Wikipedia in India after the English version. However, more than the 85% of Wikipedia pageviews by India still go to English, although between January 2016 and January 2021 the share of Hindi Wikipedia increased from 2% to 8%.[2] Most pageviews come from India. Hindi Wikipedia has more than 1,400 active users. In 2020 Hindi surpassed 2,000 active users for the first time, although in 2021 it has decreased due to COVID-19 pandemic. 
The Hindi Wikipedia (Hindi:   is the Hindi edition of Wikipedia. It was launched in July 2003. As of January 2022, it has 152,184 articles. In October 2021, there were 72 million page views.[1] On August 30, 2011, it became the first localized edition of Wikipedia in India to surpass 100,000 articles. Hindi, using the Devanagari script, requires complex transliteration aids to be typed on devices. Thus, a Phonetic Roman Alphabet converter is also available on the Hindi Wikipedia, so the Roman keyboard can be used to contribute in Hindi, without having to use any special Hindi-typing software.

Hindi Wikipedia is the second most popular Wikipedia in India after the English version. However, more than the 85% of Wikipedia pageviews by India still go to English, although between January 2016 and January 2021 the share of Hindi Wikipedia increased from 2% to 8%.[2] Most pageviews come from India. Hindi Wikipedia has more than 1,400 active users. In 2020 Hindi surpassed 2,000 active users for the first time, although in 2021 it has decreased due to COVID-19 pandemic. 
<script>
		dody.print()
</script>		
</body>

		</html>`
		c.Data(http.StatusOK, "text/html; charset=utf-8", []byte(htmlBody))
	})
	// engine.GET("/:id", func(c *gin.Context) {
	// 	controller.Get(c)
	// })
	// engine.POST("/", func(c *gin.Context) {
	// 	controller.Add(c)
	// })
	// engine.POST("/addmultiple", func(c *gin.Context) {
	// 	controller.AddMultiple(c)
	// })
}
